In [16]:
import numpy as np
#2d indexing
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array")
print(matrix)
print("Element at row 1 and column 2:",matrix[0,1])
print ("First row",matrix[0,:])
print ("second column",matrix[:,1])
print ("Submetrix(first 2 rows and first 2 columns):\n" ,matrix[0:2,0:2])



2D Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1 and column 2: 2
First row [1 2 3]
second column [2 5 8]
Submetrix(first 2 rows and first 2 columns):
 [[1 2]
 [4 5]]


In [19]:
import numpy as np
#boolean indexing
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Original",arr)
print("Elements greater than 5:",arr[arr>5])
print("Even numbers:",arr[arr%2==0])

Original [1 2 3 4 5 6 7 8 9]
Elements greater than 5: [6 7 8 9]
Even numbers: [2 4 6 8]


In [22]:
import numpy as np
#element wise operations
a = np.array([1, 2, 3])
b= np.array([4, 5, 6])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)

#Scaler Oparations
print("Add 10",a+10)

#comparision operations
print ("a>2",a>2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Add 10 [11 12 13]
a>2 [False False  True]


In [28]:
import numpy as np
#array manipulation
arr=np.arange(12)
print("Original array:",arr)

#reshape
reshape=arr.reshape(2,6)#must match 3*4=12
print("Reshaped array:\n",reshape)

#flatten
flatten=reshape.flatten()
print("Flattened array:",flatten)

#Transpose
matrix=np.array([[1,2,3],[4,5,6]])
print("Original matrix:\n",matrix)
print("Transposed:\n", matrix.T)


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Original matrix:
 [[1 2 3]
 [4 5 6]]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]


In [33]:
import numpy as np
#Statistical Operation
data = np.array([1, 2, 3, 4, 5,6,7,8,9])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard deviation:", np.std(data))
print("varience",np.var(data))
#2d
matrix=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Sum of all Elements",np.sum(matrix))
print("Sum of row",np.sum(matrix,axis=0)) #row sum
print("Sum of Column",np.sum(matrix,axis=1)) #column sum

Mean: 5.0
Median: 5.0
Standard deviation: 2.581988897471611
varience 6.666666666666667
Sum of all Elements 45
Sum of row [12 15 18]
Sum of Column [ 6 15 24]
