In [16]:
import numpy as np
#2d indexing
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array")
print(matrix)
print("Element at row 1 and column 2:",matrix[0,1])
print ("First row",matrix[0,:])
print ("second column",matrix[:,1])
print ("Submetrix(first 2 rows and first 2 columns):\n" ,matrix[0:2,0:2])



2D Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1 and column 2: 2
First row [1 2 3]
second column [2 5 8]
Submetrix(first 2 rows and first 2 columns):
 [[1 2]
 [4 5]]


In [19]:
import numpy as np
#boolean indexing
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Original",arr)
print("Elements greater than 5:",arr[arr>5])
print("Even numbers:",arr[arr%2==0])

Original [1 2 3 4 5 6 7 8 9]
Elements greater than 5: [6 7 8 9]
Even numbers: [2 4 6 8]


In [22]:
import numpy as np
#element wise operations
a = np.array([1, 2, 3])
b= np.array([4, 5, 6])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)

#Scaler Oparations
print("Add 10",a+10)

#comparision operations
print ("a>2",a>2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Add 10 [11 12 13]
a>2 [False False  True]


In [28]:
import numpy as np
#array manipulation
arr=np.arange(12)
print("Original array:",arr)

#reshape
reshape=arr.reshape(2,6)#must match 3*4=12
print("Reshaped array:\n",reshape)

#flatten
flatten=reshape.flatten()
print("Flattened array:",flatten)

#Transpose
matrix=np.array([[1,2,3],[4,5,6]])
print("Original matrix:\n",matrix)
print("Transposed:\n", matrix.T)


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Original matrix:
 [[1 2 3]
 [4 5 6]]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]


In [34]:
import numpy as np
#Statistical Operation
data = np.array([1, 2, 3, 4, 5,6,7,8,9])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard deviation:", np.std(data))
print("varience",np.var(data))
#2d
matrix=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Sum of all Elements",np.sum(matrix))
print("Sum of row",np.sum(matrix,axis=0)) #row sum
print("Sum of Column",np.sum(matrix,axis=1)) #column sum

Mean: 5.0
Median: 5.0
Standard deviation: 2.581988897471611
varience 6.666666666666667
Sum of all Elements 45
Sum of row [12 15 18]
Sum of Column [ 6 15 24]


In [ ]:
import numpy as np
Image=np.random.randint(0,256,size=(10,10))
print("Image:\n",Image)
#image operation
print("Brightness(mean):{np.mean(Image):.2f}")
print("Contrast(std):{np.std(Image):.2f}")

brighter=np.clip(Image+50,0,255)
print("brightness increased:(mean:{np.mean(brighter):.2f})")
print("Image:\n",brighter)

contrast=np.clip(Image*1.5,0,255)
print(f"Contrast increased:(std:{np.std(contrast):.2f})")
print("Image:\n",contrast)

Image:
 [[ 94  29 221 229 232 146 110  19 230 220]
 [ 52  38 175 180 194  26 117   4 122 136]
 [112 182 156 180 139 118  50 122 126 105]
 [  5 140 104 195 141  73 189  69 220  25]
 [ 79  61 121   1  18  26 145 153 149  49]
 [127 209 240 152 253  14  95  95   4  84]
 [ 18 255 140 221 190 124   9 176 148 240]
 [ 87  45  23 253 232   4 153  98 253  15]
 [131 219 225 139 149  52 190  33  13 115]
 [ 91 189 107  60 248 134   5  57 125 148]]
Brightness(mean):{np.mean(Image):.2f}
Contrast(std):{np.std(Image):.2f}
brightness increased:(mean:{np.mean(brighter):.2f})
Contrast increased:(std:87.17)
Image:
 [[141.   43.5 255.  255.  255.  219.  165.   28.5 255.  255. ]
 [ 78.   57.  255.  255.  255.   39.  175.5   6.  183.  204. ]
 [168.  255.  234.  255.  208.5 177.   75.  183.  189.  157.5]
 [  7.5 210.  156.  255.  211.5 109.5 255.  103.5 255.   37.5]
 [118.5  91.5 181.5   1.5  27.   39.  217.5 229.5 223.5  73.5]
 [190.5 255.  255.  228.  255.   21.  142.5 142.5   6.  126. ]
 [ 27.  255.  210.  